### ISSUE TITLE
When using database with '.' character, the HiLoKeyGenerator wont work

### ISSUE THREAD

**Issue by ti24horas** [atheken/NoRM#22]
Im using a database named like ti24horas.com.
When i tried to insert a new object into mongodb, the application locks up in a loop waiting for receive data and in server side an exception is thrown.
The workaround for me was rename the database to ti24horas

**Comment by atheken** [comment]
"." is reserved in MongoDB and should not be used for naming databases or collections. The reason is because "." is used as a delimiter between the elements, so MongoDB would not have a reasonable way to determine what the client meant. Regardless, NoRM should probably enforce this requirement by throwing an exception when the user defines an invalid name.
