### ISSUE TITLE
CultureInfo support

### ISSUE THREAD

**Issue by JornWildt** [atheken/NoRM#9]
I was trying to store an instance of CultureInfo. The BSON serializer crashed with a stack overflow due to the fact that CultureInfo has a Parent property which refers to itself, thereby making a circular reference.

A CultureInfo can be stored as a simple string like "en-US".

There must be a ton of simple value objects like this that cannot immediately be serialized even though they have a simple string representation. I suggest some kind of plugin structure where one can add "tostring" serializers (or more generic serializers) for certain objects. The class mapping is not really good enough here.

**Comment by petriashev** [comment]
I've added similar issue: http://github.com/atheken/NoRM/issues#issue/19

**Comment by JornWildt** [comment]
And my branch contains a solution, but so far Andrew hasn't merged it.

**Comment by petriashev** [comment]
Yes, I started to do the same thing! )))
Andrew, what about JornWildt solution?

**Comment by atheken** [comment]
I'm going to cherry-pick Jorn's TypeConverter solution, I just can't include his circular reference handling, as it would screw up query semantics for each document in a collection.

**Comment by JornWildt** [comment]
Okay, thanks. Can you explain why the circular reference stuff is wrong? Maybe I can fix it?

**Comment by JornWildt** [comment]
Tak a look at the changelists I have submitted - they are rather explicit about which features they add.

**Comment by atheken** [comment]
Jorn, here's one example:

class Product{
  string Name{get;set;}
  Supplier ProductSupplier {get;set;}
}
class Supplier{
  string Name {get;set;}
  Product BestProduct {get;set;}
}

P1 = new Product{}
S1 = new Supplier{}
P1.Name = "ACME"
P1.ProductSupplier = S1;
S1.BestProduct = P1;

coll = db.GetCollection<Product>()
coll.Insert(P1);
results = coll.AsQueryable().Where(y=>y.ProductSupplier.BestProduct.Name == "ACME");

since "BestProduct" is just a reference to P1, "Name" will not resolve correctly on the DB side, and we won't get correct results back.

I understand this is a "contrived" example, but this is a simplified version of circular references. 

The folks at 10Gen are very specific that MongoDB is a DocumentDB, not an ObjectDB, and I think the fact that it doesn't do internal dereferencing is one of the major differences.

**Comment by atheken** [comment]
By the way, I have merged in the TypeConverter code, test and all, Thank you.

**Comment by JornWildt** [comment]
You are right, NoRM/MongoDB won't be able to query correctly with circular references, I see that. But neither does it work today - NoRM crashes with a stack overflow. Adding circular references will enable some usefull scenarioes that NoRM cannot handle today - but it won't be complete with, for instance, querying as you say. But in many (my) cases that may not be an issue.

**Comment by atheken** [comment]
I think that the safest thing to do is disable the behavior by default, and throw an exception when the circular reference is detected, but allow for the user to opt-in to serializing them.

**Comment by JornWildt** [comment]
That is indeed very fine with me.
